motif = function(pattern, dna_set){
  patterns = vector()
  minimum_hd = vector()
  for (k in 1:length(dna_set)) {
    posn = 1
    min_hd = HammingDist(pattern, substr(dna_set[k], 1, (1+nchar(pattern)-1)))
    for (i in 2:(nchar(dna_set[k])-nchar(pattern)+1)) {
      hd = HammingDist(pattern, substr(dna_set[k], i, (i+nchar(pattern)-1)))
      if(hd<min_hd){
        min_hd = hd
        posn = i
      }
    }
    minimum_hd = append(minimum_hd, min_hd)
    pattern1 = substr(dna_set[k], posn, posn + nchar(pattern) - 1)
    patterns = append(patterns, pattern1)
  }
  result = list(minimum_hd, patterns)
  return(result)
}

# pattern = "GCGAT"
# dna_set = c("GACCTGCACTTCAGTAATCCGTGGGTCGACAGAGCGCCTCGACCGCACATGACTCGATCGCTCTCCCATGTGCTATTACCATCTTATTCCGTG", "AGGACGCCGGTCAACGCATTCGTACACAATCGGCCGCTGTTCCAGACCGGAGTGTGTTCCACAGTCTCTGCAGTCATTATTCCGGTGGTATCT", "TAAGCCGCAAGGATTACATAACGATTTATAGTCCCAGAATGAGTAAGCCGATCCCGATCAAACCTTATAAGCGAGTTCGGTATGTTGAGCCTA", "TGTTACAGTACCGGTAGAGTATTGCAACCCACTGAATCTGGATAGATTTGTCGCCAGGGTCTCCATCAGGCATGAGCTAACCCGGGAACCCTC", "ACTTGCTTTGCTAGGATTTTACGAATATCGTGGGGAACTTTCTAACGTGTATAACTTGTGCATTCAAAGGGTAGACGTAGAACCCAGCACCGC", "CAGCTTGAGGTCGTTGTATAGGCCACAACCTCGTTAACCAGATCGCCTCCCATTACAACACTACTCAAATGATGTATACGTTAGCGCGAAAGT", "CTCTTACTTGCATTACTGGTCCGGTTTCTGCGTCGCTTACGAGTGATGACTACAATGAGCCTTAATTAGTAAGGAATTGTGTACCATTTGAAC", "ACAACGGCTTTTCAACGAGAGCAAGGGATGTCGTACTTCTGCTGCTCCGATTGAAAGGCTCTGCCCTAAACTGGCATCAGTGTTAACGGTCCC", "TTGGTTCGTATCCAAAGTTAAAAGGACCTACACGTTGTTCAGTGTCGTCAGTGCGCAGCTGTAGCAGAGATCCAGTCCAACCAATCAAGGGTT", "ATCCGGGCTAGATGCTATTTTGTGCCGGAATACTGCGCGTAGGAAGTAAGTTCAGATACAGAAGCGTCATACATCAGAGTTAGTCAAAGTAAA", "CTCGTGAGAAGTTAACCCCCCGAACCTCGAATCGGATCTTGCACCCACGTGTTCTTGGAGTAAAGGCTGCTTTACGTTCATTCTTGTAGGCAA", "ATGGAATAAGAACGCGGACCTCGATTATCCCTCTTACCGGGAGGCCGACTCCCATCCGTGTACCTCCGCGGTGATTACAAAGCCGCCGACGCG", "ATCCCAAGTACGGTGAGGACTAAGGGCTAGGCCTCCCCCGATCTGTTTTAAAGGTGGTGACTCGGTTCCGACCCACACGGATGTGAAACGAAG", "TTTTTGGGTGAGTGTCCGACTAAACTCGATTAATGATATGTCGTAGCAGTGCCCCGGTGTTCTCCTTTTACATGACTAATGCCAGACGTACAC", "GGCGACCGTTACGTGTGGCGAGCTCCGTTCAATATGATCGAGGCGGGGGAGAGCTTTGCATTAGTGTGAGGTTGCCTATTGATCCCCAGTAAT", "TACTGAATTTCCTAGTGCTGATAATCGGCGGCCGTCCCCGCTTCATGTTGGCCGCCTAACTGGAAGACGAACACTTATTGCCGCTCCTCATCG", "ACGCACCCATGACCCATTAGCGGAGCACCGGGATCTTCCGCATAGGTGCCTTATGGCAGATCAGTGGTAGCGATTATGATGAACCACTTAGTG", "AGTTGCTGACGGCGCAACCCCGTTGGGGATATTTTCGGCCAAAACATCAATGTGCAAGTTCTGACCAGTCCCCACGTGCGAGGAGACGCCCCG", "TGCGCTTCGCTTCTACGCTTCACCTTTCCACAAGTGATCGTTCCGCATAGTAGGGTGCAAACGAGGTTAAAGACTTGTGCACCTGCTGTCTGG", "ACATGTCGGAATTATCTGCATGATCTGCAGTTCCTCGAAGCAATGATGGTTAAGGAACGGACTTCTCGCAATGTACGGATCTGACAAGGTAGT", "ATCCGGTAACCGGGTACCATCTGGTCAAGACTAGTCTGAAAGGACTAGAGCCTTAGGAACACCGCGCGATGTAGCTTATCGTGCGAGGTATAG", "ACGGGATGATTCACAGGCACGGCGCATTCGCACGTGCAGCACTACCGATGCAACTTCTGCTCTTCAGTCCACCGAAATCTGTCTAATGGACCA", "TAAGTGTCCAAGGTCCTCTTGTGCTCTTCAATGATGGACCGGTCTGAAGCACGAACGTTACGGGTGGTGTGACTTGGGCTAGGCTCCTCGCCA", "AAGTGAACCTTGGCACGTATTTCTCAGGGTGACAGTTCGAATCGGAATCATATCCCTAAATGACGGCTAGTGGCTGTCTGTGACGAGGCTGAT", "AGACACCGTTCTGCGTCGCTGTGTCGCCCGAAACCGAGTTCGGGGACTCATTTAGTTCCAGAGATGAATACCACAACCTGCCCACCTCCCCCG", "CTAAAGCCGGCGTTCGTGCATACCGTTAACCTGGACACTGCGATCTTCTAGCGACCCTGTACAAGCCCAAGCTCGCTCTAAGTGGGTGAGGAT", "ATGGTGGTGCGGGCGTTAGGTCTACAAACAGCCAGCCCGGATTCGCTGCCCTCTGGCTCTGGTGATATAAGATGTGCCGCCCCATAAAGACCG", "GGCACCTGGGAACACATCACTAATTGAATTAATTCCTCTCCCCGCGTTGTGGCTTACTATGGTCCGTAACCAGACAACATCTTCCCCAGGACA", "CTCATCCGGGCGTTCCGATTCTTGGATTACCAATAGATCCTCTCACAAATGCCCGTTGAACTCGACTGTGCGGCCGACGGCAAGCCTAATATT", "GAGTGGTGACGCCACGTGAATACTCAATTCGTGCAGAAGCTACACCGACCCCATCTTTACTAGGTGACACATTACAAACATGGCGACAGGATA", "ACTGGGCAAGGACCCTACACCGCATATCAGTCATCATTCCAGTGCTACCCAAGCGAGAATTGATCCCTCTTATGATAGCGCGCCTGCCCGAGA", "ACCCAATGGCCATACTTACTGATGATCTGTGGGGCTCAAAGGTAAGGGTCTATTCAATCTACGGGCCAGGCACCTGGTGAGTAACGTTTCATT", "CCGGACGAGCCGCCGACGTAGATACAAGCCGTCGCGCACTAGCATGTTGTGTATCGTCATTATTTTGGAAATAAGGAAATAGGAGCTTTTGAT", "ATGCAAAGCAGGCGCGATTGGAGATGAGGGCCTAAGTGGGATTGCATTTGCGTCAATAGATCTCAACGTCCTCCTGAGGTACGGGACTGATTA", "AGGGCCGAATGACCGCCGTCTAATAGGTATTTAACCGGTCTCGAATGAAAATGTCTTTCGGTGCGGTTGGAGCGTTTTTTGGATTTCCTACCT", "CCTTATACGCGATTTGCGGGCCTAGCCCACATGTTGATGTGGCTTACGAAGATAAGCGTCAAATCGGGTATAACCAAGTGTCACGATACTACT", "GTCACTCTCTCGGATTCTGCCTGAAAATTGGTCGAAGGGGTCCCCAATATCGACGAGTATGGATACCACGTCTTTAATCACCTCCGTATCTTG", "GCTATGGATTATGGGGACTTGGCTGATATAGATGTCACGGGCCACTGAAGTGGGCCCCTCTTTGAGCCGAAGTGTTCGTTTTCCGATGAATAA", "TTAACGCCTACTACCACTTTCATTTTTTTCAAAGATCCTGCATCAATTATTAAAGTTTGAGTGTCGACTGGCCTGCGGTACTGCAAGCCTAAG")
# motif = motif(pattern, dna_set)
# print(motif[1])
# print(sum(unlist(motif[1])))
# print(motif[2])

# Median = vector()
# dna_set = c("GGTGGCAG", "CGTAGGTC", "CCGTCAAG", "ACCTGAAC", "ACCGTGGA")
# distance = 999999
# k = 4
# x = '^'(4,k)
# for (i in 1:x) {
#   pattern = NumberToPattern(i,k)
#   motifd = motif(pattern, dna_set)
#   if(distance > sum(unlist(motifd[1]))){
#     distance = sum(unlist(motifd[1]))
#     Median = append(Median, pattern)
#   }
# }
# print(Median)